#-------------------------
# BUILD SETTINGS
#-------------------------

markdown: kramdown
permalink: pretty

port: 8000

# include: ['_includes/work']
# exclude: ['the_design.psd']

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
# destination: serve

sass:
  sass_dir: assets/scss
  style: :nested